imports:
  # Content
  # -> Hugolify content types and taxonomies available https://www.hugolify.io/docs/sections/

  # Core theme
  - path: https://github.com/sebousan/venn-capital
  - path: github.com/hugolify/hugolify-theme


  # CMS
  - path: github.com/hugolify/hugolify-admin
